---
steps:

  # Install pipenv, install deps, compile pipelines
  - name: python:3.9
    entrypoint: /bin/sh
    args:
      - -c
      - |
        pip install kfp jinja2 && \
        make compile-kfp-pipeline
    env:
      - PIPELINE_TEMPLATE=${_PIPELINE_TEMPLATE}


options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s  # 30mins
