---
steps:

  # Install pipenv, install deps, compile pipelines
  - name: python:3.9
    entrypoint: /bin/sh
    args:
      - -c
      - |
        pip install kfp && \
        compile-kfp-pipeline
    env:
      - PIPELINE_TEMPLATE=${_PIPELINE_TEMPLATE}

  # Copy pipelines and files to a new directory in GCS
  # (via a new local directory)
  # Directory name = git commit hash
  - name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - -c
      - |
        mkdir -p ${TAG_NAME}/training/assets && \
        mkdir -p ${TAG_NAME}/prediction/assets && \
        cp pipelines/training.json ${TAG_NAME}/training/training.json && \
        cp pipelines/prediction.json ${TAG_NAME}/prediction/prediction.json && \
        cp -r pipelines/pipelines/${_PIPELINE_TEMPLATE}/training/assets ${TAG_NAME}/training/ && \
        cp -r pipelines/pipelines/${_PIPELINE_TEMPLATE}/prediction/assets ${TAG_NAME}/prediction/ && \
        for dest in ${_PIPELINE_PUBLISH_GCS_PATHS} ; do \
          gsutil cp -r ${TAG_NAME} $$dest ; \
        done

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s  # 30mins
