---
steps:

  # Install pipenv, install deps, compile pipelines
  - name: gcr.io/tfx-oss-public/tfx:1.4.0
    entrypoint: /bin/sh
    args:
      - -c
      - |
        pip install google-cloud-aiplatform==1.7.1 kfp==1.8.1 && \
        make compile-kfp-pipeline
    env:
      - PIPELINE_TEMPLATE=${_PIPELINE_TEMPLATE}


options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s  # 30mins
