---
steps:

  # Install pipenv, install deps, compile pipelines
  - name: gcr.io/tfx-oss-public/tfx:1.0.0
    entrypoint: /bin/sh
    args:
      - -c
      - |
        pip install kfp && \
        make compile-kfp-pipeline
    env:
      - PIPELINE_TEMPLATE=${_PIPELINE_TEMPLATE}


options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s  # 30mins
