PROJECT: "strategy-bi-ltd"
REGION: "europe-west2"
SERVICE_ACCOUNT: "792237211962-compute@developer.gserviceaccount.com"
BUCKET: "mlops-gcp"
VERSION: "v01"
DATASET_DISPLAY_NAME: "useragentscikit"
RAW_SCHEMA_DIR: "titanic/raw_schema"
MLMD_SQLLITE: "mlmd.sqllite"
REMOVE_ARTIFACTS: True
MODULE_FILE: "baselineua_module.py"
TRAIN_QUERY: "SELECT user_agent, status FROM `strategy-bi-ltd.preprocessing.user_agent`"
TEST_QUERY: "SELECT user_agent, status FROM `strategy-bi-ltd.preprocessing.user_agent`"
DEST_PATH: "gs://mlops-gcp/useragent"